### PR TITLE
A couple of bug fixes in the latest version...

### LINKED ISSUE #7: Flow Type For PolicyDocument is Incorrect
First off, thanks so much for making this project!

You have the following defined
export interface PolicyDocument {
    Version: string;
    Statement: [Statement];
}

From reading the AWS documentation. Statements should be an array of statements (Array<Statement>) what you currently have is defining it as a tuple

### PR DESCRIPTION
**Pull request by designfrontier**
closes #7 and fixes the ProxyHandler type

### CODE REVIEW

**Comment by designfrontier** [comment]
@yarax the current version breaks flow checks until this patchset merges

**Comment by designfrontier** [comment]
also the change from 1.0.4 to 1.0.5 introduced ApiGateway as a polymorphic type which is a breaking change.

**Comment by yarax** [comment]
Thanks!

**Comment by designfrontier** [comment]
thanks for the quick response @yarax!

**Pull request merged**
